### ISSUE TITLE
Caxton Layout block - what should happen if a user sets a background color or image?

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/caxton#104]
Maybe we hide content block background color - cuz it's a bit strange atm

Below i set the background color of the container to red 

<img width="1117" alt="screen shot 2018-09-25 at 08 36 38" src="https://user-images.githubusercontent.com/3070779/45999736-74199700-c09e-11e8-8827-d90371fbb993.png">

**Comment by jamiemarsland** [comment]
I can't see this working in my tests?

**Comment by shramee** [comment]
Hi... we had default color opacity is set to .9 so it showed bg behind...
Now... We don't show the color when image is set and bg opacity is `1`...

**Comment by jamiemarsland** [comment]
But shouldn't the background also show through the back on the content block?
