### ISSUE TITLE
Post aren't coming into a page in the correct order

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/caxton#14]
1) Set posts to show newest first
2) Publish a new post
3) View page - newest post not showing top left
4) If you go to edit page , then the newest post is showing in the correct position. But doesn't work once published

**Comment by shramee** [comment]
Hmm... seems to work for..?
Can you confirm new post has a post image..?
It won't shows posts with out one :)
Maybe add it as an option ;)
