### ISSUE TITLE
Caxton Layout is not showing on mobile view

### ISSUE THREAD

**Issue by jchavez9790** [pootlepress/caxton#178]
Hello, I updated my Caxton Plugin (now version 1.20.0) and realized that my Caxton Layout has hidden on mobile view, is this a bug?

![Capture](https://user-images.githubusercontent.com/43855553/76337018-6bca1180-62bc-11ea-9bc2-62db4655192d.PNG)

**Comment by jamiemarsland** [comment]
Hi , are you able to send us a login so we can take a look (we have no other reports of this)

here's the link pootlepress.com/support-form

**Comment by jchavez9790** [comment]
Sorry, the problem was my CSS file.
