### ISSUE TITLE
Rename 'don't dim'

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/caxton#18]
Cuz this really means 'don't dim or don't lighten'

So lets rename to 'default'

**Comment by shramee** [comment]
Hi Jamie, we have don't dim coz that option ain't default...
By default we have a bit of dim effect so it looks good out of the box :wink:

**Comment by jamiemarsland** [comment]
So which one is the default ? how does a user get back to default?

**Comment by shramee** [comment]
We use either light for 2 col hero and dark for hero...
