### ISSUE TITLE
2 Col Hero - transparency doesn't seem to work by default

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/caxton#28]
<img width="873" alt="screen shot 2018-03-22 at 06 48 21" src="https://user-images.githubusercontent.com/3070779/37755356-16cb3f66-2d9d-11e8-9b29-fc1aa8167d4f.png">

It shows in preview fine, but not when published

<img width="715" alt="screen shot 2018-03-22 at 06 49 17" src="https://user-images.githubusercontent.com/3070779/37755397-33998b8e-2d9d-11e8-9587-dc5c69348ce5.png">

**Comment by shramee** [comment]
Hmm... Not sure I understand...
Do we have this live..?

**Comment by jamiemarsland** [comment]
Yup live and replicated everytime on socialpress.co.uk - normal login

**Comment by jamiemarsland** [comment]
Here's an example http://www.socialpress.co.uk/210-2/

No transparency

**Comment by shramee** [comment]
![image](https://user-images.githubusercontent.com/11048263/37860602-987ca47a-2f4e-11e8-9a62-257948692390.png)
![image](https://user-images.githubusercontent.com/11048263/37860604-a47bddcc-2f4e-11e8-943f-d1d05e4b839d.png)

Well it is transparent... There's nothing much to see on the background 😅 
So it appears opaque. Changing the image should make it easier to see it opacity ;)
