### ISSUE TITLE
Posts Grid - re-editing a page with posts grid often doesn't load posts

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/caxton#32]
Re-editing a page with posts grid doesn't work

Create a page, add posts grid
Pubilsh page
View page
Edit page
Post grid won't reload

**Comment by shramee** [comment]
Tried middle clicking and opening edit page about 20 times... But couldn't rep...
Could you share the console log when we reproduce..? There might be an error in there :wink:
