### ISSUE TITLE
Not an issue but a few suggestions

### ISSUE THREAD

**Issue by Theremingenieur** [pootlepress/caxton#39]
1) Besides the very beautiful post grid, I'd like to see a single post block with similar design (title, featured image, excerpt) 

2) Similar, I'd like to see a website block (based on external url) which gives a nice website preview as seen on facebook and twitter

Is that something you'd consider?

**Comment by Theremingenieur** [comment]
What can I do to motivate you to realize my suggestions?

**Comment by jamiemarsland** [comment]
Hi , well i like Guitars and Bikes :)

Here's a few questions 

1) Couldn't you just use Gutenberg for this? 

2) Could you give me an example, I'm not 100% clear on what this is

**Comment by Theremingenieur** [comment]
1st example: I select a category first, and then a single post in the toolbar and get a single post preview block like that:
![capture d ecran 2018-05-06 a 22 52 24](https://user-images.githubusercontent.com/25463159/39677750-90be8844-5180-11e8-933f-192ea736e054.png)

**Comment by Theremingenieur** [comment]
2nd example: I type or paste an URL in the toolbar and get a website preview block like that:
![capture d ecran 2018-05-06 a 22 53 01](https://user-images.githubusercontent.com/25463159/39677757-c05b5014-5180-11e8-8482-277d2a6ab3c2.png)

**Comment by Theremingenieur** [comment]
Both blocks exist already within a blocks collection plugin ("Advanced Gutenberg Blocks", https://github.com/maximebj/advanced-gutenberg-blocks). But they don't work at all and the developer seems to have abandoned the project. Although he marked the issues as "bug", he didn't do anything to fix it for more than a month... Maybe you are able to fork and fix this?
