### ISSUE TITLE
Question: multiple blocks or focus on post grid?

### ISSUE THREAD

**Issue by opicron** [pootlepress/caxton#64]
Let me start with: I love Caxton! We will continue to use it for the foreseeable future with gutenberg.

However I see added blocks and future planned blocks. This is fine but I would like to avoid our users to see all of the blocks. This is very personal flavour preference, I am aware, but I think it might be important.

The question: will Caxton be a collection of multiple blocks or focus on the Post Grid? As an secondary question: could we get the option to enable the additional blocks specifically (opt-in) in an setup?

**Comment by jamiemarsland** [comment]
Hi, yes we are working on a settings page - where you can toggle blocks :)
