### ISSUE TITLE
Super hero block - columns don't work

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/caxton#90]
Lots of strange things happening

<img width="1263" alt="screen shot 2018-08-23 at 13 05 31" src="https://user-images.githubusercontent.com/3070779/44524405-47f0ac00-a6d5-11e8-8adb-089406a85d65.png">

**Comment by shramee** [comment]
Aaah...

From GB...
 - `InnerBlocks` grouped layout is removed. Use intermediary nested inner blocks instead. See Columns / Column block for reference implementation.
